name: CI/CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
env:
  IMAGE_NAME: "webeng-project-dhbw"

jobs:
  build_push_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo "Commit - ${{ steps.vars.outputs.sha_short }}"

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/friesenjungs/${{ env.IMAGE_NAME }}:latest
          labels: commit_sha_short=${{ steps.vars.outputs.sha_short }}
        
      - uses: darmiel/yadwh-action@v1
        with:
          url: 'http://webeng.4kevr.me:9830'
          name: 'BACKEND_PROD'
          secret: ${{ secrets.STAGED_DEPLOY_SECRET }}
